name: Run Gradle Test on push
on: push
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 18

      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.10.0

      - name: Execute Gradle build
        run: ./gradlew test

