name: Run Gradle Test on push
on: push

permissions:
  id-token: write
  contents: read
  checks: write

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 18

      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.10.0

      - name: Build and Test
        run: ./gradlew clean test

      - name: Publish test results
        uses: dorny/test-reporter@v1
        if: ${{ ! cancelled() }}
        with:
          name: Gradle Tests
          path: build/test-results/test/*.xml
          reporter: java-junit

